# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/message/message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='src/message/message.proto',
  package='bitswap.message.pb',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19src/message/message.proto\x12\x12\x62itswap.message.pb\"\x98\x05\n\x07Message\x12\x36\n\x08wantlist\x18\x01 \x01(\x0b\x32$.bitswap.message.pb.Message.Wantlist\x12\x0e\n\x06\x62locks\x18\x02 \x03(\x0c\x12\x32\n\x07payload\x18\x03 \x03(\x0b\x32!.bitswap.message.pb.Message.Block\x12\x41\n\x0e\x62lockPresences\x18\x04 \x03(\x0b\x32).bitswap.message.pb.Message.BlockPresence\x12\x14\n\x0cpendingBytes\x18\x05 \x01(\x05\x1a\x88\x02\n\x08Wantlist\x12;\n\x07\x65ntries\x18\x01 \x03(\x0b\x32*.bitswap.message.pb.Message.Wantlist.Entry\x12\x0c\n\x04\x66ull\x18\x02 \x01(\x08\x1a\x8f\x01\n\x05\x45ntry\x12\r\n\x05\x62lock\x18\x01 \x01(\x0c\x12\x10\n\x08priority\x18\x02 \x01(\x05\x12\x0e\n\x06\x63\x61ncel\x18\x03 \x01(\x08\x12?\n\x08wantType\x18\x04 \x01(\x0e\x32-.bitswap.message.pb.Message.Wantlist.WantType\x12\x14\n\x0csendDontHave\x18\x05 \x01(\x08\"\x1f\n\x08WantType\x12\t\n\x05\x42lock\x10\x00\x12\x08\n\x04Have\x10\x01\x1a%\n\x05\x42lock\x12\x0e\n\x06prefix\x18\x01 \x01(\x0c\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x1aY\n\rBlockPresence\x12\x0b\n\x03\x63id\x18\x01 \x01(\x0c\x12;\n\x04type\x18\x02 \x01(\x0e\x32-.bitswap.message.pb.Message.BlockPresenceType\"+\n\x11\x42lockPresenceType\x12\x08\n\x04Have\x10\x00\x12\x0c\n\x08\x44ontHave\x10\x01\x62\x06proto3'
)



_MESSAGE_WANTLIST_WANTTYPE = _descriptor.EnumDescriptor(
  name='WantType',
  full_name='bitswap.message.pb.Message.Wantlist.WantType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Block', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Have', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=508,
  serialized_end=539,
)
_sym_db.RegisterEnumDescriptor(_MESSAGE_WANTLIST_WANTTYPE)

_MESSAGE_BLOCKPRESENCETYPE = _descriptor.EnumDescriptor(
  name='BlockPresenceType',
  full_name='bitswap.message.pb.Message.BlockPresenceType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Have', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DontHave', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=671,
  serialized_end=714,
)
_sym_db.RegisterEnumDescriptor(_MESSAGE_BLOCKPRESENCETYPE)


_MESSAGE_WANTLIST_ENTRY = _descriptor.Descriptor(
  name='Entry',
  full_name='bitswap.message.pb.Message.Wantlist.Entry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='block', full_name='bitswap.message.pb.Message.Wantlist.Entry.block', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='priority', full_name='bitswap.message.pb.Message.Wantlist.Entry.priority', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cancel', full_name='bitswap.message.pb.Message.Wantlist.Entry.cancel', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='wantType', full_name='bitswap.message.pb.Message.Wantlist.Entry.wantType', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sendDontHave', full_name='bitswap.message.pb.Message.Wantlist.Entry.sendDontHave', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=363,
  serialized_end=506,
)

_MESSAGE_WANTLIST = _descriptor.Descriptor(
  name='Wantlist',
  full_name='bitswap.message.pb.Message.Wantlist',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='entries', full_name='bitswap.message.pb.Message.Wantlist.entries', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='full', full_name='bitswap.message.pb.Message.Wantlist.full', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_MESSAGE_WANTLIST_ENTRY, ],
  enum_types=[
    _MESSAGE_WANTLIST_WANTTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=275,
  serialized_end=539,
)

_MESSAGE_BLOCK = _descriptor.Descriptor(
  name='Block',
  full_name='bitswap.message.pb.Message.Block',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='prefix', full_name='bitswap.message.pb.Message.Block.prefix', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='bitswap.message.pb.Message.Block.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=541,
  serialized_end=578,
)

_MESSAGE_BLOCKPRESENCE = _descriptor.Descriptor(
  name='BlockPresence',
  full_name='bitswap.message.pb.Message.BlockPresence',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cid', full_name='bitswap.message.pb.Message.BlockPresence.cid', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='bitswap.message.pb.Message.BlockPresence.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=580,
  serialized_end=669,
)

_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='bitswap.message.pb.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='wantlist', full_name='bitswap.message.pb.Message.wantlist', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='blocks', full_name='bitswap.message.pb.Message.blocks', index=1,
      number=2, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='payload', full_name='bitswap.message.pb.Message.payload', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='blockPresences', full_name='bitswap.message.pb.Message.blockPresences', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pendingBytes', full_name='bitswap.message.pb.Message.pendingBytes', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_MESSAGE_WANTLIST, _MESSAGE_BLOCK, _MESSAGE_BLOCKPRESENCE, ],
  enum_types=[
    _MESSAGE_BLOCKPRESENCETYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=714,
)

_MESSAGE_WANTLIST_ENTRY.fields_by_name['wantType'].enum_type = _MESSAGE_WANTLIST_WANTTYPE
_MESSAGE_WANTLIST_ENTRY.containing_type = _MESSAGE_WANTLIST
_MESSAGE_WANTLIST.fields_by_name['entries'].message_type = _MESSAGE_WANTLIST_ENTRY
_MESSAGE_WANTLIST.containing_type = _MESSAGE
_MESSAGE_WANTLIST_WANTTYPE.containing_type = _MESSAGE_WANTLIST
_MESSAGE_BLOCK.containing_type = _MESSAGE
_MESSAGE_BLOCKPRESENCE.fields_by_name['type'].enum_type = _MESSAGE_BLOCKPRESENCETYPE
_MESSAGE_BLOCKPRESENCE.containing_type = _MESSAGE
_MESSAGE.fields_by_name['wantlist'].message_type = _MESSAGE_WANTLIST
_MESSAGE.fields_by_name['payload'].message_type = _MESSAGE_BLOCK
_MESSAGE.fields_by_name['blockPresences'].message_type = _MESSAGE_BLOCKPRESENCE
_MESSAGE_BLOCKPRESENCETYPE.containing_type = _MESSAGE
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {

  'Wantlist' : _reflection.GeneratedProtocolMessageType('Wantlist', (_message.Message,), {

    'Entry' : _reflection.GeneratedProtocolMessageType('Entry', (_message.Message,), {
      'DESCRIPTOR' : _MESSAGE_WANTLIST_ENTRY,
      '__module__' : 'src.message.message_pb2'
      # @@protoc_insertion_point(class_scope:bitswap.message.pb.Message.Wantlist.Entry)
      })
    ,
    'DESCRIPTOR' : _MESSAGE_WANTLIST,
    '__module__' : 'src.message.message_pb2'
    # @@protoc_insertion_point(class_scope:bitswap.message.pb.Message.Wantlist)
    })
  ,

  'Block' : _reflection.GeneratedProtocolMessageType('Block', (_message.Message,), {
    'DESCRIPTOR' : _MESSAGE_BLOCK,
    '__module__' : 'src.message.message_pb2'
    # @@protoc_insertion_point(class_scope:bitswap.message.pb.Message.Block)
    })
  ,

  'BlockPresence' : _reflection.GeneratedProtocolMessageType('BlockPresence', (_message.Message,), {
    'DESCRIPTOR' : _MESSAGE_BLOCKPRESENCE,
    '__module__' : 'src.message.message_pb2'
    # @@protoc_insertion_point(class_scope:bitswap.message.pb.Message.BlockPresence)
    })
  ,
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'src.message.message_pb2'
  # @@protoc_insertion_point(class_scope:bitswap.message.pb.Message)
  })
_sym_db.RegisterMessage(Message)
_sym_db.RegisterMessage(Message.Wantlist)
_sym_db.RegisterMessage(Message.Wantlist.Entry)
_sym_db.RegisterMessage(Message.Block)
_sym_db.RegisterMessage(Message.BlockPresence)


# @@protoc_insertion_point(module_scope)
